# Generated by Django 5.2.7 on 2025-10-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_modules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modules',
            new_name='Module',
        ),
    ]
